FEAT(#27) insert categories adding panel
Darkosz1012/amazonka pull request #14
Opened 2021-05-19 17:07 UTC by veroniqaa

2021-05-21 03:42 UTC, pieczonkam requested changes
Apart from taking care of requested changes, please take a look at console warnings, as they seem to be directly related to Categories component

2021-05-21 03:42 UTC, pieczonkam commented on front/src/components/AdminPanel/Panel/Categories/Categories.css
> +}
Compact this piece of code

2021-05-21 03:42 UTC, pieczonkam commented on front/src/components/AdminPanel/Panel/Categories/Categories.css
> +    }
Compact it

2021-05-21 03:42 UTC, pieczonkam commented on front/src/components/AdminPanel/Panel/Categories/Categories.css
> +    }
Compact it

2021-05-21 03:42 UTC, pieczonkam commented on front/src/components/AdminPanel/Panel/Categories/Categories.js
> +                            />{" "}
Add constraint for this input, so that number of series can only be positive integer (currently it accepts negative values as well)

2021-05-21 15:40 UTC, frogi16 requested changes
One tiny thing, looks ok.
Also I like @pieczonkam's ideas

2021-05-21 15:40 UTC, frogi16 commented on front/src/components/AdminPanel/Panel/Categories/Categories.js
> +                                <option value="man" key="man"> Mężczyźni </option>
Maybe use plurals? Women, men

2021-05-22 20:31 UTC, pieczonkam requested changes

2021-05-22 20:31 UTC, pieczonkam commented on front/src/components/AdminPanel/Panel/Categories/Categories.test.js
> +});
Added extra tests and reorganized code a bit
```suggestion
import { render, screen, within } from "@testing-library/react";
import Categories from "./Categories";

describe("Categories", () => {
    beforeEach(() => {
        render(<Categories />);
    });

    describe("first form", () => {
        it("should have one input field", () => {
            let inputFields = screen.getAllByRole("textbox");
            expect(inputFields).toHaveLength(1);
        });

        it("should have one select field", () => {
            let selectInputs = screen.getAllByRole("combobox");
            expect(selectInputs).toHaveLength(1);
        });
    });

    describe("table with added categories", () => {
        it("should render", () => {
            let categoryTable = screen.getByRole("table");
            expect(categoryTable).toBeInTheDocument();
        });

        it("should have radio button in each row", () => {
            let rows = screen.getAllByRole("row");
            for (let row of rows) {
                expect(within(row).getByRole("radio")).toBeInTheDocument();
            }
        });
    });

    it("should have two buttons", () => {
        let buttons = screen.getAllByRole("button");
        expect(buttons).toHaveLength(2);
    });

    describe("after choosing a category", () => {
        beforeEach(() => {
            screen.getAllByRole("radio")[0].click();
        });

        it("should have three input fields", () => {
            let inputFields = screen.getAllByRole("textbox");
            expect(inputFields).toHaveLength(3);
        });

        it("should have one spinbutton", () => {
            let numberInputFields = screen.getAllByRole("spinbutton");
            expect(numberInputFields).toHaveLength(1);
        });

        it("should have four buttons", () => {
            let buttons = screen.getAllByRole("button");
            expect(buttons).toHaveLength(4);
        });

        it("should have two tables", () => {
            let tables = screen.getAllByRole("table");
            expect(tables).toHaveLength(2);
        });

        it("should have radio button in each row", () => {
            let rows = screen.getAllByRole("row");
            for (let row of rows) {
                expect(within(row).getByRole("radio")).toBeInTheDocument();
            }
        });
    });
});

```

2021-05-22 20:31 UTC, pieczonkam commented on front/src/components/AdminPanel/Panel/Categories/Categories.js
> +                        />
I'm not sure if that was intended but moving Button out of form results in onSubmit event not being called. Applies to Button in line 201 as well

2021-05-22 20:37 UTC, pieczonkam commented on front/src/components/AdminPanel/Panel/Categories/Categories.js
> +                        />
For some reason this request is visible as outdated but please, take a look at it

2021-05-23 16:20 UTC, frogi16 approved these changes

2021-05-23 19:29 UTC, pieczonkam approved these changes

2021-05-23 20:15 UTC, merged