feature/login panel
Darkosz1012/amazonka pull request #24
Opened 2021-05-26 09:40 UTC by veroniqaa

FEAT(#9): updating login panel and adding tests

2021-05-27 20:32 UTC, frogi16 requested changes

2021-05-27 20:32 UTC, frogi16 commented on front/src/components/LoginPanel/LoginPanel.test.js
> +        let buttonsDiv = container.querySelector(".buttons");
Querying by div or other properties invisible for user is the least preferable option, but in this case is necessary to distinguish from buttons rendered by nested components.
Consider changing class name to something specific to this and only this div or even adding some other easily-distinguishable property (role, id, etd).

2021-05-27 20:32 UTC, frogi16 commented on front/src/components/LoginPanel/LoginPanel.test.js
> +            name: /zarejestruj się/i,
If to search specifically for button, add this info to query and let react testing library do its job :)

2021-05-27 20:32 UTC, frogi16 commented on front/src/components/LoginPanel/comp/LoginForm.test.js
> +});
Rewrite this file in a way I did with LoginPanel.test.js in commit fb558db

2021-05-29 14:32 UTC, frogi16 commented on front/src/components/LoginPanel/comp/LoginForm.js
Lines 18-22:
```
    const [loginUser, { data }] = useMutation(LOGIN_USER, {
        onError(err) {
            console.log(err);
        },
    });
```
Change this to something visible to user, even alert would be better.

2021-05-30 14:19 UTC, frogi16 requested changes

2021-05-30 14:19 UTC, frogi16 commented on front/src/components/LoginPanel/comp/LoginForm.test.js
> +        ).container;
You don't use container anywhere.

2021-05-30 14:19 UTC, frogi16 commented on front/src/components/LoginPanel/comp/LoginForm.test.js
>      });
Search also by name

2021-05-30 14:19 UTC, frogi16 commented on front/src/components/LoginPanel/comp/LoginForm.test.js
> +        expect(loginButton).toBeInTheDocument();
Remove "się" in case text will ever change

2021-05-30 14:59 UTC, frogi16 commented on front/src/components/LoginPanel/comp/LoginForm.js
> +                />{" "}
Use autoComplete like in 50b47ce.

2021-05-30 16:23 UTC, frogi16 requested changes

2021-05-30 16:23 UTC, frogi16 commented on front/src/components/LoginPanel/comp/LoginForm.js
> +                    autoComplete="new-password"
Shouldn't it be?
```suggestion
                    autoComplete="current-password"
```

2021-05-30 16:23 UTC, frogi16 commented on front/src/components/LoginPanel/comp/LoginForm.test.js
> +    it("should have a textbox input for login or email", () => {
I don't think "or email" is tested here. Update test name

2021-06-01 17:53 UTC, frogi16 approved these changes

2021-06-01 18:12 UTC, pieczonkam approved these changes

2021-06-01 18:36 UTC, merged