Feature/login api
Darkosz1012/amazonka pull request #33
Opened 2021-05-29 18:05 UTC by miczoc98

Adds validation for user username, password and email in user registration

2021-05-29 23:29 UTC, pieczonkam requested changes

2021-05-29 23:29 UTC, pieczonkam commented on graphql/resolvers/user/mutations.js
> +        }
Is it necessary to wrap these validators with try/catch block? This results in some loss of information about which part is incorrect (also, there is no such try/catch block in corresponding part of register mutation).

2021-05-30 14:39 UTC, frogi16 approved these changes

2021-05-30 15:42 UTC, pieczonkam approved these changes

2021-05-30 16:43 UTC, merged