REFACTOR: add competition api usage
Darkosz1012/amazonka pull request #39
Opened 2021-06-02 14:03 UTC by MagdalenaGie

I started using competition api instead of json mocked data, please take a look.

2021-06-04 19:16 UTC, frogi16 requested changes
### **Merge commit 1cadc9a causes compilation of app to crash!**

![image](https://user-images.githubusercontent.com/44038381/120852006-f100ac80-c579-11eb-8e29-950aae83412e.png)

2021-06-05 15:45 UTC, Darkosz1012 commented on front/src/components/AdminPanel/Panel/CompetitionDetails/EditDetails/EditDetails.js
> +`;
This query is probably unnecessary.

2021-06-05 15:46 UTC, Darkosz1012 approved these changes

2021-06-05 20:01 UTC, frogi16 commented on front/src/hoc/WithProvider/WithProvider.js
> +                {children}
Maybe add a way to pass initialEntries to Router as well?

2021-06-05 20:01 UTC, frogi16 approved these changes

2021-06-06 17:38 UTC, merged