FEAT(#69): add home page with content
Darkosz1012/amazonka pull request #46
Opened 2021-06-05 18:39 UTC by Darkosz1012

2021-06-05 18:55 UTC, frogi16 requested changes
Looks OK, maybe it's to big? Empty space on the sides could look better

2021-06-05 20:12 UTC, frogi16 requested changes

2021-06-05 20:12 UTC, frogi16 commented on front/src/components/HomePage/HomePage.js
> +                    Witajcie na stronie orgazniatora zawodów łuczniczych
Typo
```suggestion
                    Witajcie na stronie organizatora zawodów łuczniczych
```

2021-06-05 20:12 UTC, frogi16 commented on front/src/components/HomePage/HomePage.js
> +                    organizatorem oraz słabą automatyzacji zawodów łuczniczych w
Typo: automatyzację

2021-06-05 20:12 UTC, frogi16 commented on front/src/components/HomePage/HomePage.js
> +                    sumowanie wyników rozpisywanie eliminacji.
```suggestion
                    sumowanie wyników, czy rozpisywanie eliminacji.
```

2021-06-05 20:12 UTC, frogi16 commented on front/src/components/HomePage/HomePage.js
> +                            strzały lub wynik serii, a nasz system wyliczy
Repetition
```suggestion
                            strzały lub wynik serii, a system wyliczy
```

2021-06-05 20:12 UTC, frogi16 commented on front/src/components/HomePage/HomePage.js
> +                            ranking wszystkim osobą, które wejdą na tą stronę.
Spelling errors
```suggestion
                            ranking wszystkim osobom, które wejdą na tę stronę.
```

2021-06-05 20:12 UTC, frogi16 commented on front/src/components/HomePage/HomePage.js
> +                            i przydzielisz im kategorie, a nasz system
Repetition
```suggestion
                            i przydzielisz im kategorie, a system
```

2021-06-05 20:12 UTC, frogi16 commented on front/src/components/HomePage/HomePage.js
> +                            Na podstawie wyników kwalifikacji, nasz system
Repetition, needless comma
```suggestion
                            Na podstawie wyników kwalifikacji system
```

2021-06-05 21:04 UTC, Darkosz1012 commented on front/src/components/HomePage/HomePage.js
> +                    organizatorem oraz słabą automatyzacji zawodów łuczniczych w
```suggestion
                    organizatorem oraz słabą automatyzację zawodów łuczniczych w
```

2021-06-05 22:19 UTC, frogi16 requested changes
I am not sure if removing package-lock is a good idea, especially without adding it to gitignore

2021-06-06 09:45 UTC, Darkosz1012 commented
> I am not sure if removing package-lock is a good idea, especially without adding it to gitignore

I didn't remove packege-lock. It rebuild itself, when I use "npm i", so I think there should not be a problem.

2021-06-06 10:04 UTC, frogi16 approved these changes

2021-06-06 11:25 UTC, pieczonkam approved these changes

2021-06-06 16:17 UTC, merged